settings:
  legacy:
    force: true
    interval: 100ms
schema:
- name: app
  path: .
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
