version: '3.4'
services:
  filedownloader:
    image: filedownloader
    build:
      context: .
      # For production, lets target the dockerfile's final container
      target: final
      dockerfile: FileDownloader/Dockerfile